### ISSUE TITLE
Cannot @ mention a user with ampersand '&' in username

### ISSUE THREAD

**Issue by steve-king** [microcosm-cc/microweb#291]
E.g. when I type @Skull_&_Biscuits in the post WYSIWYG the resulting post does not contain a link to that user.

**Comment by buro9** [comment]
@'s and +'s follow Twitter rules (as mentions do on Github too).

This means that only usernames that conform to Twitter username conventions work.

The reason is basically this:
https://github.com/microcosm-cc/microcosm/blob/master/models/mentions.go#L232-L244

This does not match on non-ASCII alphanum_- usernames because the stored profile_name is sanitised and any unicode or HTML entities are escaped.

i.e. you send in `Skull_&_Biscuits` and this is actually in the database as `Skull_&amp;_Biscuits`.

I can add a layer of sanitisation to this, which would allow most of the usernames to work even if they contain HTML entities, but this will still not match all usernames as some contain unicode non-printable characters that you cannot have typed in.

**Comment by buro9** [comment]
Hmm... no, that doesn't work.

It will remain as a wontfix.

There are multiple layers of things that appear to prevent this:
1. Markdown processing (`_` and `_` introduce emphasis)
2. HTML escaping `&` becomes `&amp;`
3. Implicit boundaries (what defines the end of a username? how about `'s` such as `@velocio's`?)
4. Context boundaries (currently mentions are processed within PRE and CODE blocks when they shouldn't be)

To keep it predictable and less buggy... I'll stick with "follows Twitter username rules" rather than trying to encompass more usernames such as those containing HTML entities, extended unicode and markup.
